# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mtm < Formula
  desc "Terminal dashboard for parallel AI agent tasks (Claude Code, Codex, Droid)"
  homepage "https://github.com/ahaaicc/mtm"
  version "0.2.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ahaaicc/mtm-releases/releases/download/v0.2.7/mtm_0.2.7_darwin_amd64.tar.gz"
      sha256 "ac6f37a6d3bd5400fbe7d3f55a9d533ceadf68b637c43ed79d14b792cc7c2d2a"

      define_method(:install) do
        bin.install "mtm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ahaaicc/mtm-releases/releases/download/v0.2.7/mtm_0.2.7_darwin_arm64.tar.gz"
      sha256 "71b9fc28d858f2f7627fcf2d28d4ce23d4d1ac73d9000980e0b9e9c09066db77"

      define_method(:install) do
        bin.install "mtm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ahaaicc/mtm-releases/releases/download/v0.2.7/mtm_0.2.7_linux_amd64.tar.gz"
      sha256 "ff3bfc3a2734629eab58454d895056eb6636ff09ea2396b16ef6c2ec3e4bfc1d"
      define_method(:install) do
        bin.install "mtm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ahaaicc/mtm-releases/releases/download/v0.2.7/mtm_0.2.7_linux_arm64.tar.gz"
      sha256 "56427bca6d54851ff92decae9b284fda73cde934142513e092d0bd97bb57ed52"
      define_method(:install) do
        bin.install "mtm"
      end
    end
  end

  def caveats
    <<~EOS
      首次使用请接入 agent 提醒：
        mtm install claude
        mtm install codex
    EOS
  end
end
