# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mtm < Formula
  desc "Terminal dashboard for parallel AI agent tasks (Claude Code, Codex, Droid)"
  homepage "https://github.com/ahaaicc/mtm"
  version "0.2.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ahaaicc/mtm-releases/releases/download/v0.2.6/mtm_0.2.6_darwin_amd64.tar.gz"
      sha256 "c00626f08efc56e2dd6d55f2a8e24bfa9557fb4ca25402a74b01728d013f1fa5"

      define_method(:install) do
        bin.install "mtm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ahaaicc/mtm-releases/releases/download/v0.2.6/mtm_0.2.6_darwin_arm64.tar.gz"
      sha256 "0c4aeabdc229011fe1d3263c9b16549df4058c3322bf8d022bfc5ad6edbf6a01"

      define_method(:install) do
        bin.install "mtm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ahaaicc/mtm-releases/releases/download/v0.2.6/mtm_0.2.6_linux_amd64.tar.gz"
      sha256 "c142f3f7ae0a97c226c511b1b3301300c9d6dc1c4eb3a13a5a749f2b5cd7f7e5"
      define_method(:install) do
        bin.install "mtm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ahaaicc/mtm-releases/releases/download/v0.2.6/mtm_0.2.6_linux_arm64.tar.gz"
      sha256 "6977a9bafd31b9843571e8c75296ed27480fa0a06c1740ce386234e192eb48af"
      define_method(:install) do
        bin.install "mtm"
      end
    end
  end

  def caveats
    <<~EOS
      首次使用请接入 agent 提醒：
        mtm install claude
        mtm install codex
    EOS
  end
end
