# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mtm < Formula
  desc "Terminal dashboard for parallel AI agent tasks (Claude Code, Codex, Droid)"
  homepage "https://github.com/ahaaicc/mtm"
  version "0.2.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ahaaicc/mtm/releases/download/v0.2.6/mtm_0.2.6_darwin_amd64.tar.gz"
      sha256 "4450256eb9ef36499e26459cbaedcf11b3d2ea0c98b36026a7d37100c2e790f8"

      define_method(:install) do
        bin.install "mtm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ahaaicc/mtm/releases/download/v0.2.6/mtm_0.2.6_darwin_arm64.tar.gz"
      sha256 "bded203cee1ff59bedc4eaa33acf60b917e2a28a5d517b8845c5f688f818d959"

      define_method(:install) do
        bin.install "mtm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ahaaicc/mtm/releases/download/v0.2.6/mtm_0.2.6_linux_amd64.tar.gz"
      sha256 "bf4f51dc3bad611f5f0a4483440f0f52f2da0c8302e19969013269ec5cd222e2"
      define_method(:install) do
        bin.install "mtm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ahaaicc/mtm/releases/download/v0.2.6/mtm_0.2.6_linux_arm64.tar.gz"
      sha256 "350a5476ce1a4178a7918fced4f6ace34fc7ab21e881febad73dbcd89ed13169"
      define_method(:install) do
        bin.install "mtm"
      end
    end
  end

  def caveats
    <<~EOS
      首次使用请接入 agent 提醒：
        mtm install claude
        mtm install codex
    EOS
  end
end
